FROM postgres:latest

ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=CSCI5400
ENV POSTGRES_DB=DataAnalysis

EXPOSE 5432:5432

COPY SentimentAnalysis.sql /docker-entrypoint-initdb.d/
VOLUME db

# If you are working in the db directory, you can.
# Build using:  docker build -t db .
# Run using:    docker run -d -p 5432:5432 -v db:/var/lib/postgresql/data db